#!/bin/bash
#
# Rebuild the lib-nonpublic binary objects.
#
# The source commit is pinned in bin/lib-nonpublic.manifest. Re-running
# the script with no --ref rebuilds from that pinned commit, so the
# binaries in bin/ are reproducible from what's in the tree. To move
# the pin to a newer source commit, pass --ref=<sha|branch> explicitly;
# the script then rewrites the manifest. Commit the manifest together
# with the rebuilt binaries so CI can verify they match.

set -euo pipefail

# Resolve paths relative to this script so it can be invoked from any cwd.
SDK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REPO_URL="${TS_LIB_NONPUBLIC_REPO_URL:-}"
REF=""
ASSUME_YES=0
DIR_CLONE="${SDK_ROOT}/lib-nonpublic"
MANIFEST="${SDK_ROOT}/bin/lib-nonpublic.manifest"

usage() {
    cat <<EOF
Usage: $(basename "$0") [--repo=<url>] [--ref=<commit|branch>] [--yes]

  --repo=<url>   lib-nonpublic repo URL. Required unless
                 TS_LIB_NONPUBLIC_REPO_URL is set. Internal devs
                 typically have it in their environment setup.
  --ref=<ref>    Commit or branch to build. If omitted, the SHA
                 recorded in ${MANIFEST} is used so re-running
                 reproduces the committed binaries. Pass --ref to
                 bump the pin to a new source commit; the manifest
                 is rewritten with the new SHA. If no manifest
                 exists yet, the script falls back to remote HEAD.
  --yes, -y      Non-interactive: delete an existing ${DIR_CLONE} without asking.

Writes ${MANIFEST} recording the source commit. Commit both the rebuilt
binaries and the manifest in the same SDK commit so a verifier can check
that the binaries match the recorded commit.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --repo=*)  REPO_URL="${1#--repo=}"; shift ;;
        --ref=*)   REF="${1#--ref=}"; shift ;;
        --yes|-y)  ASSUME_YES=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [ -z "$REPO_URL" ]; then
    echo "ERROR: lib-nonpublic repo URL not set." >&2
    echo "Pass --repo=<url> or set TS_LIB_NONPUBLIC_REPO_URL." >&2
    exit 1
fi

# Default --ref to the SHA pinned in the manifest. Bumping the pin is an
# explicit --ref override. If no manifest exists yet (bootstrap), resolve
# remote HEAD to a SHA so the rest of the script has REF set — there's no
# pin to silently overwrite in that case.
if [ -z "$REF" ]; then
    if [ -f "$MANIFEST" ]; then
        REF="$(awk '/^lib-nonpublic-commit:/ {print $2; exit}' "$MANIFEST")"
        if [ -z "$REF" ]; then
            echo "ERROR: no 'lib-nonpublic-commit:' entry in ${MANIFEST}." >&2
            echo "Pass --ref=<commit|branch> explicitly." >&2
            exit 1
        fi
        echo "Using lib-nonpublic commit from manifest: ${REF}"
    else
        REF="$(git ls-remote "$REPO_URL" HEAD | awk '{print $1; exit}')"
        if [ -z "$REF" ]; then
            echo "ERROR: could not resolve remote HEAD from ${REPO_URL}." >&2
            exit 1
        fi
        echo "NOTE: ${MANIFEST} not found — building from remote HEAD (${REF})."
    fi
fi

if [ -d "$DIR_CLONE" ]; then
    if [ "$ASSUME_YES" -ne 1 ]; then
        echo "ERROR: '${DIR_CLONE}' exists. Re-run with --yes to overwrite, or remove it first." >&2
        exit 1
    fi
    rm -rf "$DIR_CLONE"
fi

git clone "$REPO_URL" "$DIR_CLONE"
git -C "$DIR_CLONE" checkout "$REF"

LIB_NONPUBLIC_SHA="$(git -C "$DIR_CLONE" rev-parse HEAD)"

( cd "$DIR_CLONE" && ./build_nonpublic.sh --sdk="../" )

mkdir -p "$(dirname "$MANIFEST")"
{
    echo "# Auto-generated by $(basename "$0"). Do not edit by hand."
    echo "lib-nonpublic-commit: ${LIB_NONPUBLIC_SHA}"
    echo "built-at: $(date -u +%FT%TZ)"
} > "$MANIFEST"

echo
echo "Built lib-nonpublic binaries from commit ${LIB_NONPUBLIC_SHA}."
echo "Wrote ${MANIFEST}. Commit it alongside the rebuilt binaries."
