#!/bin/bash

deactivate 2>/dev/null || true

# Set TS_REPO_ROOT variable, important for compilation flow
echo "Setting TS_REPO_ROOT to: `pwd`"
export TS_REPO_ROOT=`pwd`

if command -v ts_sw_cfg.py >/dev/null 2>&1; then
    echo "ts_sw_cfg.py exists, update environment"

    # Generate temporary file which will configure SW
    ts_sw_cfg.py -v csp/umc55/ts_sw_setup.yml

    # Source it and get rid of it
    source ./source_me_to_get_all_set
    rm source_me_to_get_all_set

else
    echo "ts_sw_cfg.py does not exist, assume default docker environment"
fi

