//   Ordt 230321.02 autogenerated file 
//   Input: /projects/tropic01/work/avrba/ts-cpb/reg_map/cpb_reg_map.rdl
//   Parms: /projects/tropic01/work/avrba/ts-cpb/scripts/ordt_param_file
//   Date: Mon Aug 14 10:10:56 CEST 2023
//

#ifndef __CPB_REGISTER_MAP__
#define __CPB_REGISTER_MAP__

#include "bits.h"

/* CPB_REGISTERS memory map */
enum CPB_REGS {
  CPB_BLOCK_ID_ADDR = 0X0,
  CPB_CONFIG_ADDR = 0X4,
  CPB_STATUS_ADDR = 0X8,
  CPB_INT_EN_ADDR = 0XC,
  CPB_PCR_RES_ADDR = 0X10,
  CPB_POINTERS_ADDR = 0X14,
  CPB_CODES_ADDR = 0X18,
  CPB_CII_COUNTERS_ADDR = 0X1C
};

/* BLOCK_ID register fields */

#define CPB_BLOCK_ID_ID_CODE_MASK GENMASK(15, 0)
#define CPB_BLOCK_ID_ID_CODE_POS 0

#define CPB_BLOCK_ID_REV_CODE_MASK GENMASK(19, 16)
#define CPB_BLOCK_ID_REV_CODE_POS 16


/* CONFIG register fields */

#define CPB_CONFIG_EPCK_MASK BIT(0)
#define CPB_CONFIG_EPCK_POS 0


/* STATUS register fields */

#define CPB_STATUS_PCD_MASK BIT(0)
#define CPB_STATUS_PCD_POS 0

#define CPB_STATUS_CNA_MASK BIT(1)
#define CPB_STATUS_CNA_POS 1

#define CPB_STATUS_PCR_MASK GENMASK(11, 8)
#define CPB_STATUS_PCR_POS 8

#define CPB_STATUS_RUA_MASK BIT(12)
#define CPB_STATUS_RUA_POS 12

#define CPB_STATUS_SEC_MASK BIT(13)
#define CPB_STATUS_SEC_POS 13


/* INT_EN register fields */

#define CPB_INT_EN_PCD_EN_MASK BIT(0)
#define CPB_INT_EN_PCD_EN_POS 0

#define CPB_INT_EN_CNA_EN_MASK BIT(1)
#define CPB_INT_EN_CNA_EN_POS 1


/* PCR_RES register fields */

#define CPB_PCR_RES_CMD_ID_MASK GENMASK(7, 0)
#define CPB_PCR_RES_CMD_ID_POS 0

#define CPB_PCR_RES_COI_ID_MASK GENMASK(11, 8)
#define CPB_PCR_RES_COI_ID_POS 8


/* POINTERS register fields */

#define CPB_POINTERS_CMD_PTR_MASK GENMASK(15, 0)
#define CPB_POINTERS_CMD_PTR_POS 0

#define CPB_POINTERS_RES_PTR_MASK GENMASK(31, 16)
#define CPB_POINTERS_RES_PTR_POS 16


/* CODES register fields */

#define CPB_CODES_UNAUTHORIZED_MASK GENMASK(7, 0)
#define CPB_CODES_UNAUTHORIZED_POS 0


/* CII_COUNTERS register fields */

#define CPB_CII_COUNTERS_WRITE_CNT_MASK GENMASK(15, 0)
#define CPB_CII_COUNTERS_WRITE_CNT_POS 0

#define CPB_CII_COUNTERS_READ_CNT_MASK GENMASK(31, 16)
#define CPB_CII_COUNTERS_READ_CNT_POS 16


#endif
