//   Ordt 230321.02 autogenerated file 
//   Input: /projects/Digital_flow/work/oharielina/ts-edb/reg_map/edb_reg_map.rdl
//   Parms: /projects/Digital_flow/work/oharielina/ts-edb/scripts/ordt_param_file
//   Date: Mon Mar 04 10:52:30 CET 2024
//

#ifndef __EDB_REGISTER_MAP__
#define __EDB_REGISTER_MAP__

#include "bits.h"

/* EDB_REGISTERS memory map */
enum EDB_REGS {
  EDB_BLOCK_ID_ADDR = 0X0,
  EDB_CONFIG_ADDR = 0X4,
  EDB_STATUS_ADDR = 0X8,
  EDB_INT_EN_ADDR = 0XC,
  EDB_DEBUG_RANDOM_VAL_ADDR = 0X10
};

/* BLOCK_ID register fields */

#define EDB_BLOCK_ID_ID_CODE_MASK GENMASK(15, 0)
#define EDB_BLOCK_ID_ID_CODE_POS 0

#define EDB_BLOCK_ID_REV_CODE_MASK GENMASK(19, 16)
#define EDB_BLOCK_ID_REV_CODE_POS 16


/* CONFIG register fields */

#define EDB_CONFIG_MODE_MASK GENMASK(2, 0)
#define EDB_CONFIG_MODE_POS 0

#define EDB_CONFIG_DBGWT_MASK BIT(3)
#define EDB_CONFIG_DBGWT_POS 3

#define EDB_CONFIG_KCKRNDS_MASK GENMASK(11, 4)
#define EDB_CONFIG_KCKRNDS_POS 4

#define EDB_CONFIG_TRAWTH_MASK GENMASK(22, 12)
#define EDB_CONFIG_TRAWTH_POS 12

#define EDB_CONFIG_ENPYRNDS_MASK GENMASK(26, 23)
#define EDB_CONFIG_ENPYRNDS_POS 23

#define EDB_CONFIG_DMYRNDS_MASK GENMASK(30, 27)
#define EDB_CONFIG_DMYRNDS_POS 27


/* STATUS register fields */

#define EDB_STATUS_DTRPND_MASK BIT(0)
#define EDB_STATUS_DTRPND_POS 0

#define EDB_STATUS_RAWCNT_MASK GENMASK(26, 16)
#define EDB_STATUS_RAWCNT_POS 16


/* INT_EN register fields */

#define EDB_INT_EN_DTRPND_INT_EN_MASK BIT(1)
#define EDB_INT_EN_DTRPND_INT_EN_POS 1


/* DEBUG_RANDOM_VAL register fields */

#define EDB_DEBUG_RANDOM_VAL_VAL_MASK GENMASK(31, 0)
#define EDB_DEBUG_RANDOM_VAL_VAL_POS 0


#endif
