//   Ordt 220422.01 autogenerated file 
//   Input: /projects/tropic01/work/oille/tassic/modules/ts-cpu-subsystem/reg_map/ftc_reg_map.rdl
//   Parms: /projects/tropic01/work/oille/tassic/modules/ts-cpu-subsystem/scripts/ordt_param_file
//   Date: Fri May 20 13:32:13 CEST 2022
//

#ifndef __FTC_REGISTER_MAP__
#define __FTC_REGISTER_MAP__

#include <bits.h>

/* FTC_REGISTERS memory map */
enum FTC_REGS {
  FTC_STATUS_ADDR = 0x0,
  FTC_MSG_BUF_CTRL_ADDR = 0x4,
  FTC_MSG_BUF_IN_ADDR = 0x8,
  FTC_RNM_DRAM_OFFSET_ADDR = 0xc,
  FTC_RNM_CTRL_ADDR = 0x10,
  FTC_FW_TO_TB_0_ADDR = 0x40,
  FTC_FW_TO_TB_1_ADDR = 0x44,
  FTC_FW_TO_TB_2_ADDR = 0x48,
  FTC_FW_TO_TB_3_ADDR = 0x4c,
  FTC_TB_TO_FW_0_ADDR = 0x80,
  FTC_TB_TO_FW_1_ADDR = 0x84,
  FTC_TB_TO_FW_2_ADDR = 0x88,
  FTC_TB_TO_FW_3_ADDR = 0x8c,
};
/*------------------------*/

/* STATUS registers */
#define FTC_STATUS_STATUS_VAL_MASK GENMASK(31, 0)
#define FTC_STATUS_STATUS_VAL_POS 0

/*------------------------*/

/* MSG_BUF_CTRL registers */
#define FTC_MSG_BUF_CTRL_MSG_BUF_CTRL_VAL_MASK GENMASK(31, 0)
#define FTC_MSG_BUF_CTRL_MSG_BUF_CTRL_VAL_POS 0

/*------------------------*/

/* MSG_BUF_IN registers */
#define FTC_MSG_BUF_IN_MSG_CHAR_MASK GENMASK(7, 0)
#define FTC_MSG_BUF_IN_MSG_CHAR_POS 0

/*------------------------*/

/* RNM_DRAM_OFFSET registers */
#define FTC_RNM_DRAM_OFFSET_RNM_DRAM_OFFSET_VAL_MASK GENMASK(31, 0)
#define FTC_RNM_DRAM_OFFSET_RNM_DRAM_OFFSET_VAL_POS 0

/*------------------------*/

/* RNM_CTRL registers */
#define FTC_RNM_CTRL_RNM_GET_MASK BIT(0)
#define FTC_RNM_CTRL_RNM_GET_POS 0

/*------------------------*/

/* FW_TO_TB_0 registers */
#define FTC_FW_TO_TB_0_FW_TO_TB_0_VAL_MASK GENMASK(31, 0)
#define FTC_FW_TO_TB_0_FW_TO_TB_0_VAL_POS 0

/*------------------------*/

/* FW_TO_TB_1 registers */
#define FTC_FW_TO_TB_1_FW_TO_TB_1_VAL_MASK GENMASK(31, 0)
#define FTC_FW_TO_TB_1_FW_TO_TB_1_VAL_POS 0

/*------------------------*/

/* FW_TO_TB_2 registers */
#define FTC_FW_TO_TB_2_FW_TO_TB_2_VAL_MASK GENMASK(31, 0)
#define FTC_FW_TO_TB_2_FW_TO_TB_2_VAL_POS 0

/*------------------------*/

/* FW_TO_TB_3 registers */
#define FTC_FW_TO_TB_3_FW_TO_TB_3_VAL_MASK GENMASK(31, 0)
#define FTC_FW_TO_TB_3_FW_TO_TB_3_VAL_POS 0

/*------------------------*/

/* TB_TO_FW_0 registers */
#define FTC_TB_TO_FW_0_TB_TO_FW_0_VAL_MASK GENMASK(31, 0)
#define FTC_TB_TO_FW_0_TB_TO_FW_0_VAL_POS 0

/*------------------------*/

/* TB_TO_FW_1 registers */
#define FTC_TB_TO_FW_1_TB_TO_FW_1_VAL_MASK GENMASK(31, 0)
#define FTC_TB_TO_FW_1_TB_TO_FW_1_VAL_POS 0

/*------------------------*/

/* TB_TO_FW_2 registers */
#define FTC_TB_TO_FW_2_TB_TO_FW_2_VAL_MASK GENMASK(31, 0)
#define FTC_TB_TO_FW_2_TB_TO_FW_2_VAL_POS 0

/*------------------------*/

/* TB_TO_FW_3 registers */
#define FTC_TB_TO_FW_3_TB_TO_FW_3_VAL_MASK GENMASK(31, 0)
#define FTC_TB_TO_FW_3_TB_TO_FW_3_VAL_POS 0


#endif
