
/**
 * @file tassic_defs.h
 * @author Tropic Square
 * @brief Tassic_defs top base address definitions.
 * @note Autogenerated by Ts Mem Map Builder v0.39 at 11:27AM on April 12, 2024 (hash 58E0D2450CD7AA89E4C215B3B21F506E7CF8DDC5E502315F1C4A8476073C895C).
 *
 * @license For the license see file LICENSE.txt file in the root directory of this source tree.
 */

#ifndef TASSIC_DEFS_H
#define TASSIC_DEFS_H

#define TROPIC01_MEMORY_MAP_CPUSS_BASE_ADDR                           0x00000000
#define TROPIC01_MEMORY_MAP_SOCCTRL_BASE_ADDR                         0x02000000
#define TROPIC01_MEMORY_MAP_SCNTR_BASE_ADDR                           0x02010000
#define TROPIC01_MEMORY_MAP_MBIST_BASE_ADDR                           0x02020000
#define TROPIC01_MEMORY_MAP_SS_BASE_ADDR                              0x03000000
#define TROPIC01_MEMORY_MAP_SCB_BASE_ADDR                             0x04000000
#define TROPIC01_MEMORY_MAP_CPB_BASE_ADDR                             0x04010000
#define TROPIC01_MEMORY_MAP_MACANDD_BASE_ADDR                         0x04020000
#define TROPIC01_MEMORY_MAP_SPECT_BASE_ADDR                           0x04030000
#define TROPIC01_MEMORY_MAP_FSS_BASE_ADDR                             0x05000000
#define TROPIC01_MEMORY_MAP_OTP_MEMORY_BASE_ADDR                      0x06000000
#define TROPIC01_MEMORY_MAP_EDB_BASE_ADDR                             0x07000000
#define TROPIC01_MEMORY_MAP_KDB_BASE_ADDR                             0x07010000
#define TROPIC01_MEMORY_MAP_BDRK_BASE_ADDR                            0x08000000

#define CPUSS_I_ROM_BASE_ADDR                                         0x00000000
#define CPUSS_I_RAM_BASE_ADDR                                         0x00100000
#define CPUSS_D_RAM_BASE_ADDR                                         0x00200000
#define CPUSS_IRQ_CTRL_BASE_ADDR                                      0x01000000
#define CPUSS_TIMER_1_BASE_ADDR                                       0x01100000
#define CPUSS_TIMER_2_BASE_ADDR                                       0x01200000

#define SOCCTRL_REG_MAP_BASE_ADDR                                     0x02000000

#define SCNTR_REG_MAP_BASE_ADDR                                       0x02010000

#define MBIST_REGISTER_MAP_BASE_ADDR                                  0x02020000

#define SS_REG_MAP_BASE_ADDR                                          0x03000000
#define SS_REQQ_BASE_ADDR                                             0x03001000
#define SS_RSPQ_BASE_ADDR                                             0x03002000

#define SCB_REG_MAP_BASE_ADDR                                         0x04000000

#define CPB_CPB_BASE_ADDR                                             0x04010000
#define CPB_DESC_MEM_BASE_ADDR                                        0x04010100
#define CPB_CMD_BUF_BASE_ADDR                                         0x04011000
#define CPB_RES_BUF_BASE_ADDR                                         0x04011800

#define MACANDD_REGMAP_BASE_ADDR                                      0x04020000

#define SPECT_D_RAM_IN_BASE_ADDR                                      0x04030000
#define SPECT_D_RAM_OUT_BASE_ADDR                                     0x04031000
#define SPECT_REG_MAP_BASE_ADDR                                       0x04032000
#define SPECT_C_ROM_BASE_ADDR                                         0x04033000
#define SPECT_E_MEM_IN_BASE_ADDR                                      0x04034000
#define SPECT_E_MEM_OUT_BASE_ADDR                                     0x04035000
#define SPECT_I_MEM_BASE_ADDR                                         0x04038000

#define FSS_FMM_BASE_ADDR                                             0x05000000
#define FSS_RAM_BUF_BASE_ADDR                                         0x05080000
#define FSS_REG_MAP_BASE_ADDR                                         0x05080200

#define OTP_MEMORY_OTP_MEMORY_BLOCK_BASE_ADDR                         0x06000000
#define OTP_MEMORY_OTP_CONTROLLER_REGISTER_MAP_BASE_ADDR              0x06002000

#define EDB_REG_MAP_BASE_ADDR                                         0x07000000

#define KDB_REG_MAP_BASE_ADDR                                         0x07010000
#define KDB_CONFIG_MEM_BASE_ADDR                                      0x07011000

#define BDRK_SECCLK_BASE_ADDR                                         0x08000000
#define BDRK_PUF_BASE_ADDR                                            0x08001000
#define BDRK_PTRNG0_BASE_ADDR                                         0x08002000
#define BDRK_PTRNG1_BASE_ADDR                                         0x08003000
#define BDRK_SHLD_BASE_ADDR                                           0x08004000
#define BDRK_SHLD2_BASE_ADDR                                          0x08005000

#endif // ! TASSIC_DEFS_H