//   Ordt 230321.02 autogenerated file 
//   Input: /home/ostanicek/repos/tassic-validation/modules/ts-sw-sdk/ipc/ipc.rdl
//   Parms: /home/ostanicek/repos/tassic-validation/modules/ts-sw-sdk/scripts/ordt_param_file
//   Date: Fri Aug 09 15:22:04 CEST 2024
//

#ifndef __IPC_REGISTER_MAP__
#define __IPC_REGISTER_MAP__

#include "bits.h"

/* IPC_REGISTERS memory map */
enum IPC_REGS {
  IPC_MSG_ID_1_ADDR = 0X0,
  IPC_MSG_ID_2_ADDR = 0X4,
  IPC_CPU_TO_PARENT_0_ADDR = 0X8,
  IPC_CPU_TO_PARENT_63_ADDR = 0X104,
  IPC_PARENT_TO_CPU_0_ADDR = 0X108,
  IPC_PARENT_TO_CPU_63_ADDR = 0X204
};

/* MSG_ID_1 register fields */

#define IPC_MSG_ID_1_CPU_BUSY_MASK BIT(0)
#define IPC_MSG_ID_1_CPU_BUSY_POS 0

#define IPC_MSG_ID_1_CPU_DONE_MASK BIT(1)
#define IPC_MSG_ID_1_CPU_DONE_POS 1

#define IPC_MSG_ID_1_MSG_SIZE_MASK GENMASK(9, 2)
#define IPC_MSG_ID_1_MSG_SIZE_POS 2

#define IPC_MSG_ID_1_MSG_TYPE_MASK GENMASK(13, 10)
#define IPC_MSG_ID_1_MSG_TYPE_POS 10

/* MSG_TYPE field values */
enum MSG_TYPE_VALUES_T {
IPC_MSG_ID_1_GENERIC = 0x1,
IPC_MSG_ID_1_STR = 0x2,
};

#define IPC_MSG_ID_1_MSG_CMD_MASK GENMASK(17, 14)
#define IPC_MSG_ID_1_MSG_CMD_POS 14

/* MSG_CMD field values */
enum MSG_CMD_VALUES_T {
IPC_MSG_ID_1_PASS = 0x3,
IPC_MSG_ID_1_FAIL = 0x2,
IPC_MSG_ID_1_GET_RND = 0x4,
IPC_MSG_ID_1_GET_DATA = 0x5,
IPC_MSG_ID_1_BULK_TRANSFER = 0x6,
};


/* MSG_ID_2 register fields */

#define IPC_MSG_ID_2_PARENT_BUSY_MASK BIT(0)
#define IPC_MSG_ID_2_PARENT_BUSY_POS 0

#define IPC_MSG_ID_2_PARENT_DONE_MASK BIT(1)
#define IPC_MSG_ID_2_PARENT_DONE_POS 1

#define IPC_MSG_ID_2_MSG_SIZE_MASK GENMASK(9, 2)
#define IPC_MSG_ID_2_MSG_SIZE_POS 2

#define IPC_MSG_ID_2_MSG_TYPE_MASK GENMASK(13, 10)
#define IPC_MSG_ID_2_MSG_TYPE_POS 10

#define IPC_MSG_ID_2_MSG_CMD_MASK GENMASK(17, 14)
#define IPC_MSG_ID_2_MSG_CMD_POS 14


/* CPU_TO_PARENT_0 register fields */

#define IPC_CPU_TO_PARENT_0_CPU_TO_PARENT_DATA_MASK GENMASK(31, 0)
#define IPC_CPU_TO_PARENT_0_CPU_TO_PARENT_DATA_POS 0


/* CPU_TO_PARENT_63 register fields */

#define IPC_CPU_TO_PARENT_63_CPU_TO_PARENT_DATA_MASK GENMASK(31, 0)
#define IPC_CPU_TO_PARENT_63_CPU_TO_PARENT_DATA_POS 0


/* PARENT_TO_CPU_0 register fields */

#define IPC_PARENT_TO_CPU_0_PARENT_TO_CPU_DATA_MASK GENMASK(31, 0)
#define IPC_PARENT_TO_CPU_0_PARENT_TO_CPU_DATA_POS 0


/* PARENT_TO_CPU_63 register fields */

#define IPC_PARENT_TO_CPU_63_PARENT_TO_CPU_DATA_MASK GENMASK(31, 0)
#define IPC_PARENT_TO_CPU_63_PARENT_TO_CPU_DATA_POS 0


#endif
