//   Ordt 230321.02 autogenerated file 
//   Input: /projects/tropic01/work/vmasek/ts-spect/reg_map/reg_map.rdl
//   Parms: /projects/tropic01/work/vmasek/ts-spect/scripts/ordt_param_file
//   Date: Mon Feb 26 13:54:00 CET 2024
//

#ifndef __SPECT_REGISTER_MAP__
#define __SPECT_REGISTER_MAP__

#include "bits.h"

/* SPECT_REGISTERS memory map */
enum SPECT_REGS {
  SPECT_BLOCK_ID_ADDR = 0X0,
  SPECT_COMMAND_ADDR = 0X4,
  SPECT_STATUS_ADDR = 0X8,
  SPECT_INT_ENA_ADDR = 0XC,
  SPECT_CONFIG_ADDR = 0X10
};

/* BLOCK_ID register fields */

#define SPECT_BLOCK_ID_ID_CODE_MASK GENMASK(15, 0)
#define SPECT_BLOCK_ID_ID_CODE_POS 0

#define SPECT_BLOCK_ID_REV_CODE_MASK GENMASK(19, 16)
#define SPECT_BLOCK_ID_REV_CODE_POS 16


/* COMMAND register fields */

#define SPECT_COMMAND_START_MASK BIT(0)
#define SPECT_COMMAND_START_POS 0

#define SPECT_COMMAND_SOFT_RESET_MASK BIT(1)
#define SPECT_COMMAND_SOFT_RESET_POS 1


/* STATUS register fields */

#define SPECT_STATUS_IDLE_MASK BIT(0)
#define SPECT_STATUS_IDLE_POS 0

#define SPECT_STATUS_DONE_MASK BIT(1)
#define SPECT_STATUS_DONE_POS 1

#define SPECT_STATUS_ERR_MASK BIT(2)
#define SPECT_STATUS_ERR_POS 2


/* INT_ENA register fields */

#define SPECT_INT_ENA_INT_DONE_EN_MASK BIT(0)
#define SPECT_INT_ENA_INT_DONE_EN_POS 0

#define SPECT_INT_ENA_INT_ERR_EN_MASK BIT(1)
#define SPECT_INT_ENA_INT_ERR_EN_POS 1


/* CONFIG register fields */

#define SPECT_CONFIG_RF_SCRAM_INIT_MASK BIT(0)
#define SPECT_CONFIG_RF_SCRAM_INIT_POS 0

#define SPECT_CONFIG_RF_SCRAM_EN_MASK BIT(1)
#define SPECT_CONFIG_RF_SCRAM_EN_POS 1


#endif
