//   Ordt 230321.02 autogenerated file 
//   Input: /projects/tropic01/work/oille/tassic_head/modules/ts-cpu-subsystem/reg_map/timer_reg_map.rdl
//   Parms: /projects/tropic01/work/oille/tassic_head/modules/ts-cpu-subsystem/scripts/ordt_param_file
//   Date: Thu Jan 04 18:13:13 CET 2024
//

#ifndef __TIMER_REGISTER_MAP__
#define __TIMER_REGISTER_MAP__

#include "bits.h"

/* TIMER_REGISTERS memory map */
enum TIMER_REGS {
  TIMER_BLOCK_ID_ADDR = 0X0,
  TIMER_CONFIG_ADDR = 0X4,
  TIMER_STATUS_ADDR = 0X8,
  TIMER_INT_EN_ADDR = 0XC,
  TIMER_M_TIME_CMP_ADDR = 0X10,
  TIMER_PRESCALER_ADDR = 0X14,
  TIMER_M_TIME_ADDR = 0X18
};

/* BLOCK_ID register fields */

#define TIMER_BLOCK_ID_ID_CODE_MASK GENMASK(15, 0)
#define TIMER_BLOCK_ID_ID_CODE_POS 0

#define TIMER_BLOCK_ID_REV_CODE_MASK GENMASK(19, 16)
#define TIMER_BLOCK_ID_REV_CODE_POS 16


/* CONFIG register fields */

#define TIMER_CONFIG_EN_MASK BIT(0)
#define TIMER_CONFIG_EN_POS 0

#define TIMER_CONFIG_THRST_MASK BIT(1)
#define TIMER_CONFIG_THRST_POS 1


/* STATUS register fields */

#define TIMER_STATUS_TIME_CMP_INT_MASK BIT(0)
#define TIMER_STATUS_TIME_CMP_INT_POS 0

#define TIMER_STATUS_OVRFL_INT_MASK BIT(1)
#define TIMER_STATUS_OVRFL_INT_POS 1


/* INT_EN register fields */

#define TIMER_INT_EN_TIME_CMP_INT_EN_MASK BIT(0)
#define TIMER_INT_EN_TIME_CMP_INT_EN_POS 0

#define TIMER_INT_EN_OVRFL_INT_EN_MASK BIT(1)
#define TIMER_INT_EN_OVRFL_INT_EN_POS 1


/* M_TIME_CMP register fields */

#define TIMER_M_TIME_CMP_M_TIME_CMP_VAL_MASK GENMASK(31, 0)
#define TIMER_M_TIME_CMP_M_TIME_CMP_VAL_POS 0


/* PRESCALER register fields */

#define TIMER_PRESCALER_PRESCALER_MASK GENMASK(15, 0)
#define TIMER_PRESCALER_PRESCALER_POS 0


/* M_TIME register fields */

#define TIMER_M_TIME_M_TIME_VAL_MASK GENMASK(31, 0)
#define TIMER_M_TIME_M_TIME_VAL_POS 0


#endif
